<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VilleTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $villes = [
            ['name' => "Cotonou", 'pays_id' => 23],
            ['name' => "Abomey-Calavi", 'pays_id' => 23],
            ['name' => "Porto-Novo", 'pays_id' => 23],
            ['name' => "Parakou", 'pays_id' => 23],
            ['name' => "Djougou", 'pays_id' => 23],
            ['name' => "Bohicon", 'pays_id' => 23],
            ['name' => "Natitingou", 'pays_id' => 23],
            ['name' => "Savé", 'pays_id' => 23],
            ['name' => "Abomey", 'pays_id' => 23],
            ['name' => "Nikki", 'pays_id' => 23],
            ['name' => "Lokossa", 'pays_id' => 23],
            ['name' => "Ouidah", 'pays_id' => 23],
            ['name' => "Dogbo-Tota", 'pays_id' => 23],
            ['name' => "Kandi", 'pays_id' => 23],
            ['name' => "Cové", 'pays_id' => 23],
            ['name' => "Malanville", 'pays_id' => 23],
            ['name' => "Pobé", 'pays_id' => 23],
            ['name' => "Kérou", 'pays_id' => 23],
            ['name' => "Savalou", 'pays_id' => 23],
            ['name' => "Sakété", 'pays_id' => 23],
            ['name' => "Comè", 'pays_id' => 23],
            ['name' => "Bembéréké", 'pays_id' => 23],
            ['name' => "Bassila", 'pays_id' => 23],
            ['name' => "Banikoara", 'pays_id' => 23],
            ['name' => "Kétou", 'pays_id' => 23],
            ['name' => "Dassa-Zoumè", 'pays_id' => 23],
            ['name' => "Tchaourou", 'pays_id' => 23],
            ['name' => "Allada", 'pays_id' => 23],
            ['name' => "Aplahoué", 'pays_id' => 23],
            ['name' => "Tanguiéta", 'pays_id' => 23],
            ['name' => "N'Dali", 'pays_id' => 23],
            ['name' => "Segbana", 'pays_id' => 23],
            ['name' => "Athiémé", 'pays_id' => 23],
            ['name' => "Grand Popo", 'pays_id' => 23],
            ['name' => "Kouandé", 'pays_id' => 23],

            ['name' => "Ouagadougou", 'pays_id' => 34],
            ['name' => "Bobo-Dioulasso", 'pays_id' => 34],
            ['name' => "Koudougou", 'pays_id' => 34],
            ['name' => "Banfora", 'pays_id' => 34],
            ['name' => "Ouahigouya", 'pays_id' => 34],
            ['name' => "Dédougou", 'pays_id' => 34],
            ['name' => "Pissila", 'pays_id' => 34],
            ['name' => "Kaya", 'pays_id' => 34],
            ['name' => "Tanghin-Dassouri", 'pays_id' => 34],
            ['name' => "Tenkodogo", 'pays_id' => 34],
            ['name' => "Pouytenga", 'pays_id' => 34],
            ['name' => "Fada N'Gourma", 'pays_id' => 34],
            ['name' => "Kordié", 'pays_id' => 34],
            ['name' => "Ouargaye", 'pays_id' => 34],
            ['name' => "Garango", 'pays_id' => 34],
            ['name' => "Dori", 'pays_id' => 34],
            ['name' => "Kongoussi", 'pays_id' => 34],
            ['name' => "Kokologo", 'pays_id' => 34],
            ['name' => "Réo", 'pays_id' => 34],
            ['name' => "Diapaga", 'pays_id' => 34],
            ['name' => "Houndé", 'pays_id' => 34],
            ['name' => "Kouka", 'pays_id' => 34],
            ['name' => "Yako", 'pays_id' => 34],
            ['name' => "Djibo", 'pays_id' => 34],
            ['name' => "Khyon", 'pays_id' => 34],
            ['name' => "Léo", 'pays_id' => 34],
            ['name' => "Nouna", 'pays_id' => 34],
            ['name' => "Pô", 'pays_id' => 34],
            ['name' => "Koupéla", 'pays_id' => 34],
            ['name' => "Zorgho", 'pays_id' => 34],
            ['name' => "Kombissiri", 'pays_id' => 34],
            ['name' => "Orodara", 'pays_id' => 34],
            ['name' => "Gourcy", 'pays_id' => 34],
            ['name' => "Tougan", 'pays_id' => 34],
            ['name' => "Boulsa", 'pays_id' => 34],
            ['name' => "Titao", 'pays_id' => 34],
            ['name' => "Manga", 'pays_id' => 34],
            ['name' => "Pama", 'pays_id' => 34],
            ['name' => "Boromo", 'pays_id' => 34],
            ['name' => "Diébougou", 'pays_id' => 34],
            ['name' => "Ziniaré", 'pays_id' => 34],
            ['name' => "Dano", 'pays_id' => 34],
            ['name' => "Boussé", 'pays_id' => 34],
            ['name' => "Solenzo", 'pays_id' => 34],

            ['name' => "Abidjan", 'pays_id' => 53],
            ['name' => "Bouaké", 'pays_id' => 53],
            ['name' => "Daloa", 'pays_id' => 53],
            ['name' => "Yamoussoukro", 'pays_id' => 53],
            ['name' => "San-Pédro", 'pays_id' => 53],
            ['name' => "Divo", 'pays_id' => 53],
            ['name' => "Korhogo", 'pays_id' => 53],
            ['name' => "Anyama", 'pays_id' => 53],
            ['name' => "Abengourou", 'pays_id' => 53],
            ['name' => "Man", 'pays_id' => 53],
            ['name' => "Gagnoa", 'pays_id' => 53],
            ['name' => "Soubré", 'pays_id' => 53],
            ['name' => "Agboville", 'pays_id' => 53],
            ['name' => "Dabou", 'pays_id' => 53],
            ['name' => "Grand-Bassam", 'pays_id' => 53],
            ['name' => "Bouaflé", 'pays_id' => 53],
            ['name' => "Issia", 'pays_id' => 53],
            ['name' => "Sinfra", 'pays_id' => 53],
            ['name' => "Katiola", 'pays_id' => 53],
            ['name' => "Bingerville", 'pays_id' => 53],
            ['name' => "Adzopé", 'pays_id' => 53],
            ['name' => "Séguéla", 'pays_id' => 53],
            ['name' => "Bondoukou", 'pays_id' => 53],
            ['name' => "Oumé", 'pays_id' => 53],
            ['name' => "Ferkessedougou", 'pays_id' => 53],
            ['name' => "Odienné", 'pays_id' => 53],
            ['name' => "Duékoué", 'pays_id' => 53],
            ['name' => "Danané", 'pays_id' => 53],
            ['name' => "Tingréla", 'pays_id' => 53],
            ['name' => "Guiglo", 'pays_id' => 53],
            ['name' => "Boundiali", 'pays_id' => 53],
            ['name' => "Agnibilékrou", 'pays_id' => 53],
            ['name' => "Daoukro", 'pays_id' => 53],
            ['name' => "Vavoua", 'pays_id' => 53],
            ['name' => "Zuénoula", 'pays_id' => 53],
            ['name' => "Tiassalé", 'pays_id' => 53],
            ['name' => "Toumodi", 'pays_id' => 53],
            ['name' => "Akoupé", 'pays_id' => 53],
            ['name' => "Lakota", 'pays_id' => 53],

            ['name' => "Accra", 'pays_id' => 83],
            ['name' => "Kumasi", 'pays_id' => 83],
            ['name' => "Tamale", 'pays_id' => 83],
            ['name' => "Sekondi-Takoradi", 'pays_id' => 83],
            ['name' => "Ashaiman", 'pays_id' => 83],
            ['name' => "Sunyani", 'pays_id' => 83],
            ['name' => "Cape Coast", 'pays_id' => 83],
            ['name' => "Obuasi", 'pays_id' => 83],
            ['name' => "Teshie", 'pays_id' => 83],
            ['name' => "Tema", 'pays_id' => 83],
            ['name' => "Madina", 'pays_id' => 83],
            ['name' => "Koforidua", 'pays_id' => 83],
            ['name' => "Wa", 'pays_id' => 83],
            ['name' => "Techiman", 'pays_id' => 83],
            ['name' => "Ho", 'pays_id' => 83],
            ['name' => "Nungua", 'pays_id' => 83],
            ['name' => "Lashibi", 'pays_id' => 83],
            ['name' => "Dome", 'pays_id' => 83],
            ['name' => "Gbawe", 'pays_id' => 83],
            ['name' => "Bawku", 'pays_id' => 83],
            ['name' => "Aflao", 'pays_id' => 83],
            ['name' => "Agona Swedru", 'pays_id' => 83],
            ['name' => "Bolgatanga", 'pays_id' => 83],
            ['name' => "Berekum", 'pays_id' => 83],
            ['name' => "Nkawkaw", 'pays_id' => 83],
            ['name' => "Winneba", 'pays_id' => 83],
            ['name' => "Hohoe", 'pays_id' => 83],
            ['name' => "Yendi", 'pays_id' => 83],
            ['name' => "Kintampo", 'pays_id' => 83],
            ['name' => "Mampong", 'pays_id' => 83],
            ['name' => "Wenchi", 'pays_id' => 83],
            ['name' => "Tarkwa", 'pays_id' => 83],
            ['name' => "Kintampo", 'pays_id' => 83],
            ['name' => "Axim", 'pays_id' => 83],
            ['name' => "Apam", 'pays_id' => 83],
            ['name' => "Salaga", 'pays_id' => 83],
            ['name' => "Keta", 'pays_id' => 83],
            ['name' => "Aburi", 'pays_id' => 83],
            ['name' => "Anomabu", 'pays_id' => 83],
            ['name' => "Kibi", 'pays_id' => 83],

            ['name' => "Lomé", 'pays_id' => 218],
            ['name' => "Sokodé", 'pays_id' => 218],
            ['name' => "Kara", 'pays_id' => 218],
            ['name' => "Kpalimé", 'pays_id' => 218],
            ['name' => "Atakpamé", 'pays_id' => 218],
            ['name' => "Bassar", 'pays_id' => 218],
            ['name' => "Tsévié", 'pays_id' => 218],
            ['name' => "Aného", 'pays_id' => 218],
            ['name' => "Mango", 'pays_id' => 218],
            ['name' => "Dapaong", 'pays_id' => 218],
            ['name' => "Tchamba", 'pays_id' => 218],
            ['name' => "Niamtougou", 'pays_id' => 218],
            ['name' => "Bafilo", 'pays_id' => 218],
            ['name' => "Notsé", 'pays_id' => 218],
            ['name' => "Sotouboua", 'pays_id' => 218],
            ['name' => "Vogan", 'pays_id' => 218],
            ['name' => "Badou", 'pays_id' => 218],
            ['name' => "Biankouri", 'pays_id' => 218],
            ['name' => "Tabligbo", 'pays_id' => 218],
            ['name' => "Kandé", 'pays_id' => 218],
            ['name' => "Amlamé", 'pays_id' => 218],
            ['name' => "Galangachi", 'pays_id' => 218],
            ['name' => "Kpagouda", 'pays_id' => 218],
        ];
        DB::table('villes')->insert($villes);
    }
}
